In [20]:
import pandas as pd

df = pd.read_csv("diamonds.csv")   # adjust path if needed
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [19]:
print(df.dtypes)
print(df[['cut','color','clarity']].head())

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object
       cut color clarity
0    Ideal     E     SI2
1  Premium     E     SI1
2     Good     E     VS1
3  Premium     I     VS2
4     Good     J     SI2

In [21]:
print(df.dtypes)
print(df[['cut','color','clarity']].head())

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object
       cut color clarity
0    Ideal     E     SI2
1  Premium     E     SI1
2     Good     E     VS1
3  Premium     I     VS2
4     Good     J     SI2

In [23]:
X = df_encoded.drop('price', axis=1)
y = df_encoded['price']

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
X_train

,carat,depth,table,x,y,z,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
26546,2.01,58.1,64.0,8.23,8.19,4.77,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
9159,1.01,60.0,60.0,6.57,6.49,3.92,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False
14131,1.10,62.5,58.0,6.59,6.54,4.10,False,False,True,False,...,True,False,False,False,False,False,False,True,False,False
15757,1.50,61.5,65.0,7.21,7.17,4.42,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
24632,1.52,62.1,57.0,7.27,7.32,4.53,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,1.05,62.4,59.0,6.48,6.51,4.05,False,False,False,True,...,False,True,False,False,False,False,False,True,False,False
44732,0.47,61.0,55.0,5.03,5.01,3.06,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
38158,0.33,60.3,58.0,4.49,4.46,2.70,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
860,0.90,62.8,59.0,6.13,6.03,3.82,False,False,True,False,...,False,False,True,False,True,False,False,False,False,False
15795,1.14,60.4,58.0,6.82,6.79,4.11,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False

In [28]:
X_test

,carat,depth,table,x,y,z,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
1388,0.24,62.1,56.0,3.97,4.00,2.47,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
50052,0.58,60.0,57.0,5.44,5.42,3.26,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
41645,0.40,62.1,55.0,4.76,4.74,2.95,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
42377,0.43,60.8,57.0,4.92,4.89,2.98,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
17244,1.55,62.3,55.0,7.44,7.37,4.61,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44081,0.50,61.6,59.0,5.06,5.14,3.14,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
23713,0.25,61.6,57.0,4.05,4.07,2.50,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
31375,0.31,58.0,62.0,4.42,4.47,2.58,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
21772,1.23,62.5,54.0,6.85,6.82,4.27,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
4998,1.08,63.2,59.0,6.40,6.57,4.10,True,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MSE: 1288705.4778516744
R²: 0.9189331350419387